# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-11 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20180704_1751'),
        ('email', '0002_auto_20180710_1007'),
    ]

    operations = [
    ]
