# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-26 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_workoutlog_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='cycle',
            field=models.CharField(choices=[('Microcycle', 'Microcycle - 1 week plan'), ('Mesocycle', 'Mesocycle - 2 to 6 week plan'), ('Macrocycle', 'Macrocycle - 1 year plan')], max_length=10, null=True, verbose_name='Periodization cycle'),
        ),
    ]
